### ISSUE TITLE
25844 isn't creature entry and not referenced from loot

### ISSUE THREAD

**Issue by garfieldbanks** [tkn963/mod-groupquests#3]
This is in my Errors.log:
`Table 'creature_loot_template' Entry 25844 isn't creature entry and not referenced from loot, and thus useless.`

I noticed a similar error message was in the message history of #2.

I ran grep and found this:
grep -r 25844 .
./mod_groupquests_creature_questitem.sql:DELETE FROM `creature_questitem` WHERE `CreatureEntry`=25844 AND `ItemId`=35222;
./mod_groupquests_creature_questitem.sql:INSERT INTO `creature_questitem` (`CreatureEntry`, `Idx`, `ItemId`) VALUES (25844, 0, 35222);
./mod_groupquests_creature_loot_template.sql:DELETE FROM `creature_loot_template` WHERE `Entry`=25844 AND `Item`=35222;
./mod_groupquests_creature_loot_template.sql:INSERT INTO `creature_loot_template` (`Entry`, `Item`, `Chance`, `QuestRequired`, `Comment`) VALUES (25844, 35222, 45, 1, 'Northsea Thug - Shipment of Animal Parts');

Is this a problem with my install or is it a problem with groupquests?

**Comment by noisiver** [comment]
I have seen this myself but haven't fixed it until now. I've just been too busy.

Also, apologies for getting to your issue report this late but for some reason I had notifications turned off and didn't know it was here. I have turned them back on now though.

Thank you for reporting it nevertheless and I just commited a fix for it so I'm closing this issue.
